name       : lifeograph
version    : 1.4.2
release    : 4
source     :
    - https://launchpad.net/lifeograph/trunk/1.4.2/+download/lifeograph-1.4.2.tar.bz2 : c7ff8930fb2c3935435ad3ecc513587ace9b14dac157b3d5cbaef8729393f7b0
license    : GPL-3.0-or-later
component  : office.notes
summary    : Lifeograph is an off-line and private journal and note taking application
description: |
    Lifeograph is an off-line and private journal and note taking application
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gtkmm-3.0)
    - intltool
    - libgcrypt-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 build/lifeograph.desktop $installdir/usr/share/applications/lifeograph.desktop
