name       : lifeograph
version    : 1.6.0.1
release    : 6
source     :
    - https://launchpad.net/lifeograph/trunk/1.6.0/+download/lifeograph-1.6.0.1.tar.xz : 0ad14d4e285464046ef4614cf86160dd2008ece8bd76cf1bcfab95a1fb2be7ce
license    : GPL-3.0-or-later
component  : office.notes
summary    : Lifeograph is an off-line and private journal and note taking application
description: |
    Lifeograph is an off-line and private journal and note taking application
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtkmm-3.0)
    - intltool
    - libgcrypt-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
