name       : lifeograph
version    : 1.5.1
release    : 5
source     :
    - https://launchpad.net/lifeograph/trunk/1.5.1/+download/lifeograph-1.5.1.1.tar.bz2 : 0d0384c9baa36a5016197e8dfa4ec12b0bd392dfd485f07158ddb3d7db2f2c82
license    : GPL-3.0-or-later
component  : office.notes
summary    : Lifeograph is an off-line and private journal and note taking application
description: |
    Lifeograph is an off-line and private journal and note taking application
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtkmm-3.0)
    - intltool
    - libgcrypt-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 build/lifeograph.desktop $installdir/usr/share/applications/lifeograph.desktop
